Ria 3306 hearing notification
hmcts/ia-home-office-integration-api pull request #142
Opened 2020-10-16 07:13 UTC by jkumar-moj

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-3306

### Change description ###
Changes to send hearing notification to HO

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2020-10-19 11:26 UTC, Lee365 requested changes
83.5% Coverage to improve

2020-10-19 11:26 UTC, Lee365 commented on src/main/java/uk/gov/hmcts/reform/iahomeofficeintegrationapi/domain/entities/HomeOfficeCaseStatus.java
> +    public HomeOfficeCaseStatus(Person person,
Constructor has 10 parameters, which is greater than 7 authorized.

2020-10-22 15:53 UTC, Lee365 approved these changes
LGTM

2020-11-19 17:28 UTC, Srihari-Nakkala approved these changes
LGTM

2021-01-06 15:48 UTC, jkumar-moj commented
re-opening the PR as it was closed automatically by stale bot

2021-01-06 16:54 UTC, merged