Ria 3310 reheard case
hmcts/ia-home-office-integration-api pull request #163
Opened 2020-11-12 12:57 UTC by Lee365

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-3310

### Change description ###
RIA-3310 reheard case changes

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2020-11-16 13:49 UTC, jkumar-moj requested changes
@Lee365 Looks good functionally but I think we need to have a handler test to verify the scenario and the notification content differentiating the reheard header.

2020-11-17 14:01 UTC, jkumar-moj approved these changes

2020-12-08 13:06 UTC, Srihari-Nakkala approved these changes
LGTM

2021-01-14 14:33 UTC, jkumar-moj commented
Reopening the PR as it was closed by stale bot

2021-01-14 17:08 UTC, merged